apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: foundry
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /foundry_data
              name: foundry-data
          ports:
            - containerPort: {{ .Values.container.port }}
              name: foundry
          imagePullPolicy: Always
      restartPolicy: Always
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: foundry-data
          persistentVolumeClaim:
            {{- if .Values.persistence.existingClaim }}
            claimName: {{ .Values.persistence.existingClaim }}
            {{- end }}
            {{- if .Values.persistence.existingClaim }}
            claimName: {{ .Values.persistence.claimName }}
            {{- end }}

      {{- end }}
