{{- if .Values.persistence.enabled && not .Values.persistence.claimName.existing }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc-foundry
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.persistence.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
