apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}
spec:
  ports:
    - name: foundry
      port: {{ .Values.container.port }}
  selector:
    app: {{ .Values.app.name }}
