app:
  name: "foundry"

persistence:
  enabled: false
  storageClassName: "default"
  claimName: "data-pvc-foundry"
  size: 2Gi
  existingClaim: ""

ingress:
  enabled: false
  hosts:
    - "www.example.com"
  className: "nginx"
  forceSSlRedirect: false
  ssl:
    enabled: false
    clusterIssuer:
      enabled: false
      name: "letsencrypt"

image:
  name: "macskay/foundry"
  tag: "latest"
  pullSecret: ""

container:
  port: 30000
